name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        run: sbt test

      - name: Coverage report
        run: |
          sbt coverage coverageReport

      - name: Assembly
        run: sbt "clean; set test in assembly := {}; assembly"

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/scala-2.13/TodoBackend-assembly-0.1.0-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts

      - name: Deploy to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: TodoBackend-assembly-0.1.0-SNAPSHOT.jar
          remote: /home/todo/builds/TodoBackend-assembly-0.1.0-SNAPSHOT.jar
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}